# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/cpp_projects/spiderOneSuitSolitaire

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/cpp_projects/spiderOneSuitSolitaire

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/cpp_projects/spiderOneSuitSolitaire/CMakeFiles /home/user/cpp_projects/spiderOneSuitSolitaire/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/cpp_projects/spiderOneSuitSolitaire/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spider

# Build rule for target.
spider: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spider
.PHONY : spider

# fast build rule for target.
spider/fast:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/build
.PHONY : spider/fast

src/AnimationWrapper.o: src/AnimationWrapper.cpp.o

.PHONY : src/AnimationWrapper.o

# target to build an object file
src/AnimationWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/AnimationWrapper.cpp.o
.PHONY : src/AnimationWrapper.cpp.o

src/AnimationWrapper.i: src/AnimationWrapper.cpp.i

.PHONY : src/AnimationWrapper.i

# target to preprocess a source file
src/AnimationWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/AnimationWrapper.cpp.i
.PHONY : src/AnimationWrapper.cpp.i

src/AnimationWrapper.s: src/AnimationWrapper.cpp.s

.PHONY : src/AnimationWrapper.s

# target to generate assembly for a file
src/AnimationWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/AnimationWrapper.cpp.s
.PHONY : src/AnimationWrapper.cpp.s

src/AnimationWrapperST.o: src/AnimationWrapperST.cpp.o

.PHONY : src/AnimationWrapperST.o

# target to build an object file
src/AnimationWrapperST.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/AnimationWrapperST.cpp.o
.PHONY : src/AnimationWrapperST.cpp.o

src/AnimationWrapperST.i: src/AnimationWrapperST.cpp.i

.PHONY : src/AnimationWrapperST.i

# target to preprocess a source file
src/AnimationWrapperST.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/AnimationWrapperST.cpp.i
.PHONY : src/AnimationWrapperST.cpp.i

src/AnimationWrapperST.s: src/AnimationWrapperST.cpp.s

.PHONY : src/AnimationWrapperST.s

# target to generate assembly for a file
src/AnimationWrapperST.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/AnimationWrapperST.cpp.s
.PHONY : src/AnimationWrapperST.cpp.s

src/Card.o: src/Card.cpp.o

.PHONY : src/Card.o

# target to build an object file
src/Card.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Card.cpp.o
.PHONY : src/Card.cpp.o

src/Card.i: src/Card.cpp.i

.PHONY : src/Card.i

# target to preprocess a source file
src/Card.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Card.cpp.i
.PHONY : src/Card.cpp.i

src/Card.s: src/Card.cpp.s

.PHONY : src/Card.s

# target to generate assembly for a file
src/Card.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Card.cpp.s
.PHONY : src/Card.cpp.s

src/ControllerSpider.o: src/ControllerSpider.cpp.o

.PHONY : src/ControllerSpider.o

# target to build an object file
src/ControllerSpider.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ControllerSpider.cpp.o
.PHONY : src/ControllerSpider.cpp.o

src/ControllerSpider.i: src/ControllerSpider.cpp.i

.PHONY : src/ControllerSpider.i

# target to preprocess a source file
src/ControllerSpider.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ControllerSpider.cpp.i
.PHONY : src/ControllerSpider.cpp.i

src/ControllerSpider.s: src/ControllerSpider.cpp.s

.PHONY : src/ControllerSpider.s

# target to generate assembly for a file
src/ControllerSpider.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ControllerSpider.cpp.s
.PHONY : src/ControllerSpider.cpp.s

src/DealOneRound.o: src/DealOneRound.cpp.o

.PHONY : src/DealOneRound.o

# target to build an object file
src/DealOneRound.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/DealOneRound.cpp.o
.PHONY : src/DealOneRound.cpp.o

src/DealOneRound.i: src/DealOneRound.cpp.i

.PHONY : src/DealOneRound.i

# target to preprocess a source file
src/DealOneRound.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/DealOneRound.cpp.i
.PHONY : src/DealOneRound.cpp.i

src/DealOneRound.s: src/DealOneRound.cpp.s

.PHONY : src/DealOneRound.s

# target to generate assembly for a file
src/DealOneRound.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/DealOneRound.cpp.s
.PHONY : src/DealOneRound.cpp.s

src/DeckSpades.o: src/DeckSpades.cpp.o

.PHONY : src/DeckSpades.o

# target to build an object file
src/DeckSpades.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/DeckSpades.cpp.o
.PHONY : src/DeckSpades.cpp.o

src/DeckSpades.i: src/DeckSpades.cpp.i

.PHONY : src/DeckSpades.i

# target to preprocess a source file
src/DeckSpades.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/DeckSpades.cpp.i
.PHONY : src/DeckSpades.cpp.i

src/DeckSpades.s: src/DeckSpades.cpp.s

.PHONY : src/DeckSpades.s

# target to generate assembly for a file
src/DeckSpades.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/DeckSpades.cpp.s
.PHONY : src/DeckSpades.cpp.s

src/FillFoundationPile.o: src/FillFoundationPile.cpp.o

.PHONY : src/FillFoundationPile.o

# target to build an object file
src/FillFoundationPile.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/FillFoundationPile.cpp.o
.PHONY : src/FillFoundationPile.cpp.o

src/FillFoundationPile.i: src/FillFoundationPile.cpp.i

.PHONY : src/FillFoundationPile.i

# target to preprocess a source file
src/FillFoundationPile.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/FillFoundationPile.cpp.i
.PHONY : src/FillFoundationPile.cpp.i

src/FillFoundationPile.s: src/FillFoundationPile.cpp.s

.PHONY : src/FillFoundationPile.s

# target to generate assembly for a file
src/FillFoundationPile.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/FillFoundationPile.cpp.s
.PHONY : src/FillFoundationPile.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/ModelSpider.o: src/ModelSpider.cpp.o

.PHONY : src/ModelSpider.o

# target to build an object file
src/ModelSpider.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ModelSpider.cpp.o
.PHONY : src/ModelSpider.cpp.o

src/ModelSpider.i: src/ModelSpider.cpp.i

.PHONY : src/ModelSpider.i

# target to preprocess a source file
src/ModelSpider.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ModelSpider.cpp.i
.PHONY : src/ModelSpider.cpp.i

src/ModelSpider.s: src/ModelSpider.cpp.s

.PHONY : src/ModelSpider.s

# target to generate assembly for a file
src/ModelSpider.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ModelSpider.cpp.s
.PHONY : src/ModelSpider.cpp.s

src/Move.o: src/Move.cpp.o

.PHONY : src/Move.o

# target to build an object file
src/Move.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Move.cpp.o
.PHONY : src/Move.cpp.o

src/Move.i: src/Move.cpp.i

.PHONY : src/Move.i

# target to preprocess a source file
src/Move.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Move.cpp.i
.PHONY : src/Move.cpp.i

src/Move.s: src/Move.cpp.s

.PHONY : src/Move.s

# target to generate assembly for a file
src/Move.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/Move.cpp.s
.PHONY : src/Move.cpp.s

src/ViewSpider.o: src/ViewSpider.cpp.o

.PHONY : src/ViewSpider.o

# target to build an object file
src/ViewSpider.cpp.o:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ViewSpider.cpp.o
.PHONY : src/ViewSpider.cpp.o

src/ViewSpider.i: src/ViewSpider.cpp.i

.PHONY : src/ViewSpider.i

# target to preprocess a source file
src/ViewSpider.cpp.i:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ViewSpider.cpp.i
.PHONY : src/ViewSpider.cpp.i

src/ViewSpider.s: src/ViewSpider.cpp.s

.PHONY : src/ViewSpider.s

# target to generate assembly for a file
src/ViewSpider.cpp.s:
	$(MAKE) -f CMakeFiles/spider.dir/build.make CMakeFiles/spider.dir/src/ViewSpider.cpp.s
.PHONY : src/ViewSpider.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... spider"
	@echo "... src/AnimationWrapper.o"
	@echo "... src/AnimationWrapper.i"
	@echo "... src/AnimationWrapper.s"
	@echo "... src/AnimationWrapperST.o"
	@echo "... src/AnimationWrapperST.i"
	@echo "... src/AnimationWrapperST.s"
	@echo "... src/Card.o"
	@echo "... src/Card.i"
	@echo "... src/Card.s"
	@echo "... src/ControllerSpider.o"
	@echo "... src/ControllerSpider.i"
	@echo "... src/ControllerSpider.s"
	@echo "... src/DealOneRound.o"
	@echo "... src/DealOneRound.i"
	@echo "... src/DealOneRound.s"
	@echo "... src/DeckSpades.o"
	@echo "... src/DeckSpades.i"
	@echo "... src/DeckSpades.s"
	@echo "... src/FillFoundationPile.o"
	@echo "... src/FillFoundationPile.i"
	@echo "... src/FillFoundationPile.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/ModelSpider.o"
	@echo "... src/ModelSpider.i"
	@echo "... src/ModelSpider.s"
	@echo "... src/Move.o"
	@echo "... src/Move.i"
	@echo "... src/Move.s"
	@echo "... src/ViewSpider.o"
	@echo "... src/ViewSpider.i"
	@echo "... src/ViewSpider.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

